config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :shifts

  root to: 'workers#index'

  get '/workers/:id/delete', to: 'workers#delete_worker', as: 'delete_worker'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :worker
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_many :shifts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shifts_controller.rb
# app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    before_action :set_shift, only: [:show, :edit, :update, :destroy]
  
    def index
      @shifts = Shift.all
    end
  
    def show
    end
  
    def new
      @shift = Shift.new
    end
  
    def create
      @shift = Shift.new(shift_params)
      if @shift.save
        redirect_to shifts_path, notice: 'Shift was successfully created.'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @shift.update(shift_params)
        redirect_to shifts_path, notice: 'Shift was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @shift.destroy
      redirect_to shifts_path, notice: 'Shift was successfully deleted.'
    end
  
    private
  
    def set_shift
      @shift = Shift.find(params[:id])
    end
  
    def shift_params
      params.require(:shift).permit(:start_date, :worker_id)
    end
  end
  

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
    def index
      @workers = Worker.all
    end
  
    def new
      @worker = Worker.new
    end
  
    def create
      @worker = Worker.new(worker_params)
      if @worker.save
        redirect_to workers_path
      else
        render 'new'
      end
    end

    def show
        @worker = Worker.find(params[:id])
        @shifts = @worker.shifts
    end
  
    def edit
      @worker = Worker.find(params[:id])
    end
  
    def update
      
      @worker = Worker.find(params[:id])
      if @worker.update(worker_params)
        redirect_to workers_path
      else
        render 'edit'
      end
    end
  
    def destroy
        binding.pry
        @worker = Worker.find(params[:id])
        @worker.destroy
        redirect_to workers_path
    end

    def delete_worker
        @worker = Worker.find(params[:id])
        @worker.shifts.destroy_all
        if @worker.destroy
          redirect_to workers_path, notice: 'Worker deleted successfully.'
        else
          redirect_to workers_path, alert: 'Failed to delete worker.'
        end
    end
    
  
    private
  
    def worker_params
      params.require(:worker).permit(:name, :status)
    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Edulib</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to "Edulib", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">

          <li class="nav-item">
            <%= link_to "Workers", workers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shifts", shifts_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/shifts/edit.html.erb
<div class="container">
  <h1>Edit Shift</h1>

  <%= form_with(model: @shift, url: shift_path(@shift), local: true, method: :patch) do |form| %>
    <div class="mb-3">
      <%= form.label :start_date, class: "form-label" %>
      <%= form.datetime_local_field :start_date, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :worker_id, class: "form-label" %>
      <%= form.collection_select :worker_id, Worker.all, :id, :name, { prompt: "Select Worker" }, class: "form-control" %>
    </div>

    <%= form.submit "Update Shift", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shifts/index.html.erb
<div class="container">
  <h1>Shifts</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Start Date</th>
        <th>Worker</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @shifts.each do |shift| %>
        <tr>
          <td><%= shift.start_date %></td>
          <td><%= shift.worker.name %></td>
          <td>
            <%= link_to 'Edit', edit_shift_path(shift), class: "btn btn-primary" %>
          </td>
          <td>
            <%= link_to 'Delete', shift_path(shift), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Shift', new_shift_path, class: "btn btn-success" %>
</div>

app/views/shifts/new.html.erb
<div class="container">
  <h1>New Shift</h1>

  <%= form_with(model: @shift, url: shifts_path, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :start_date, class: "form-label" %>
      <%= form.datetime_local_field :start_date, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :worker_id, class: "form-label" %>
      <%= form.collection_select :worker_id, Worker.all, :id, :name, { prompt: "Select Worker" }, class: "form-control" %>
    </div>

    <%= form.submit "Create Shift", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shifts/show.html.erb
<div class="container">
  <h1>Shift Details</h1>

  <h3>Start Date: <%= @shift.start_date %></h3>
  <h3>Worker: <%= @shift.worker.name %></h3>

  <%= link_to 'Edit', edit_shift_path(@shift), class: "btn btn-primary" %>
  <%= link_to 'Back to Shifts', shifts_path, class: "btn btn-secondary" %>
</div>

app/views/workers/edit.html.erb
<div class="container">
  <h1>Edit Worker</h1>

  <%= form_with(model: @worker, url: worker_path(@worker), method: :patch, class: "form") do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :status %>
      <%= form.text_field :status, class: "form-control" %>
    </div>

    <%= form.submit "Update Worker", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/workers/index.html.erb
<div class="container">
  <h1>Workers</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @workers.each do |worker| %>
        <tr>
          <td><%= worker.name %></td>
          <td><%= worker.status %></td>
          <td>
            <%= link_to 'Show', worker_path(worker), class: "btn btn-primary" %>
          

          <%= link_to 'Edit', edit_worker_path(worker), class: "btn btn-primary" %>
          
            <a href="/workers/<%= worker.id %>/delete" class="btn btn-danger" 
             data-method="delete">Delete</a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Worker', new_worker_path, class: "btn btn-success" %>
</div>

app/views/workers/new.html.erb
<div class="container">
  <h1>New Worker</h1>

  <%= form_with(model: @worker, url: workers_path, class: "form") do |form| %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group mb-4">
      <%= form.label :status %>
      <%= form.text_field :status, class: "form-control" %>
    </div>
    
    <%= form.submit "Create Worker", class: "btn btn-primary" %>
  
  <% end %>
</div>

app/views/workers/show.html.erb
<div class="container">
  <h1>Worker Details</h1>

  <h3>Name: <%= @worker.name %></h3>
  <h3>Status: <%= @worker.status %></h3>

  <h2>Shifts:</h2>
  <% if @shifts.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Start Date</th>
        </tr>
      </thead>
      <tbody>
        <% @shifts.each do |shift| %>
          <tr>
            <td><%= shift.start_date %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No shifts found for this worker.</p>
  <% end %>

  <%= link_to 'Edit', edit_worker_path(@worker), class: "btn btn-primary" %>
  <%= link_to 'Back to Workers', workers_path, class: "btn btn-secondary" %>
</div>